spring:
  profiles:
    active: prod

security:
  filter-order: 2

google-cloud-platform:
  google-cloud-storage:
    bucket-name: foodmenulist.appspot.com
---

spring:
  profiles: dev

---

spring:
  profiles: prod
